### ISSUE TITLE
Read from swagger.yaml rather than from swagger.json

### ISSUE THREAD

**Issue by GeorgBraun** [kingsquare/swagger-sequelize#4]
In case you want to read from a `swagger.yaml` rather than from a `swagger.json`, you could replace the JSON-import

```js
var swaggerSpec = JSON.parse(fs.readFileSync('<your swagger.sjon>', 'utf-8'));
```

with a YAML-import
```js
var yaml = require('js-yaml');
var swaggerSpec = yaml.safeLoad(fs.readFileSync('<your swagger.yaml>', 'utf8'));
```

To be consistent, we should "officially" add js-yaml to the project (its already there due to other modules, but you never know):

```
npm install --save js-yaml
```

If you like this, you are welcome to add this option to your README.md.

**Comment by Reggino** [comment]
Thanks for your feedback, i've updated the README accordingly.
