### ISSUE TITLE
Generation fails with swagger.json from petstore example

### ISSUE THREAD

**Issue by dlarr** [kingsquare/swagger-sequelize#5]
Hello I am trying to use this library in order to generate all sequelize stuff for my project from a swagger.json file.

Here is the swagger.json coming directly from the petstore example : http://petstore.swagger.io/v2/swagger.json

When using swagger-sequelize, to get the Pet model with : 
```
const Pet =  sequelize.define('Pet', swaggerSequelize.generate(swaggerSpec.definitions.Pet));
```

Here is the outcome:
```
Warning: encountered "#/definitions/Category"
Cannot handle $ref (yet?), falling back to blob
Warning: encountered {"type":"array","xml":{"name":"photoUrl","wrapped":true},"items":{"type":"string"}}
Can only handle array for postgres (yet?), see http://docs.sequelizejs.com/en/latest/api/datatypes/#array, falling back to blob
Warning: encountered {"type":"array","xml":{"name":"tag","wrapped":true},"items":{"$ref":"#/definitions/Tag"}}
Can only handle array for postgres (yet?), see http://docs.sequelizejs.com/en/latest/api/datatypes/#array, falling back to blob

// logging the result :
Pet generated :
class extends Model {}
```

There are a lot of warning couldn't handle this and that, but nothing get generated.

Is there anything to do ?

**Comment by dlarr** [comment]
In fact it works as intended, appart from the following things (that are listed as warnings)

* can't handle refs to define return types
* can't handle arrays

I will have to pull this project, because I want to generate FILES from this.
* sequelize models
* dao layer that will have to be fullfiled by the dev

**Comment by Reggino** [comment]
Thanks for the feedback!
